knpu_oauth2_client:
    clients:
        google:
            type: google
            client_id: "%env(OAUTH_GOOGLE_ID)%"
            client_secret: "%env(OAUTH_GOOGLE_SECRET)%"
            redirect_route: app_oauth_check
            redirect_params:
                service: google
        facebook:
            type: facebook
            client_id: "%env(OAUTH_FACEBOOK_ID)%"
            client_secret: "%env(OAUTH_FACEBOOK_SECRET)%"
            redirect_route: app_oauth_check
            redirect_params:
                service: facebook
            graph_api_version: v8.0
