twig:
    default_path: "%kernel.project_dir%/templates"
    form_themes:
        - "bootstrap_4_layout.html.twig"
        - "twig/form/birthdate.html.twig"
    paths:
        "assets/email": email

when@test:
    twig:
        strict_variables: true
